trigger:
- feature-ahp-pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'gabrielgmns/portplace'

steps:
- task: Maven@4
  inputs:
    azureSubscription: 'portplacebackend-connection'
    mavenPomFile: 'pom.xml'
    options: '-X -DskipTests'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Build com Maven'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: DockerInstaller@0
  displayName: 'Instalar o Docker'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - Gabriel'
    command: 'login'

- task: Docker@2
  displayName: 'Build da imagem Docker'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageName):latest

- task: Docker@2
  displayName: 'Push da imagem para o Docker Hub'
  inputs:
    command: 'push'
    tags: |
      $(imageName):latest

- task: AzureCLI@2
  displayName: 'Deploy no Azure Container Apps'
  inputs:
    azureSubscription: 'portplacebackend-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az containerapp update \
        --name $(CONTAINERAPPNAME) \
        --resource-group $(RESOURCEGROUPNAME) \
        --image $(imageName):latest