trigger:
- feature-ahp-pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'portplacebackend'

stages:
- stage: Build_and_Test
  displayName: 'Build and Test'
  jobs:
  - job: Build
    steps:

    - task: JavaToolInstaller@1
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        DB_URL="$(DB_URL)"
        DB_USERNAME="$(DB_USERNAME)"
        DB_PASSWORD="$(DB_PASSWORD)"
        DRIVER_CLASS="$(DRIVER_CLASS)"
        SECRET_KEY="1234"
        echo $DB_URL
        echo $DB_USERNAME
        echo $DB_PASSWORD
        echo $DRIVER_CLASS
        echo $SECRET_KEY
        mvn package\
         -DDB_URL=$DB_URL \
         -DDB_USERNAME=$DB_USERNAME \
         -DDB_PASSWORD=$DB_PASSWORD \
         -DDRIVER_CLASS=$DRIVER_CLASS \
         -DSECRET_KEY=$SECRET_KEY

    - task: Maven@4
      inputs:
        azureSubscription: 'portplacebackend-connection'
        mavenPomFile: 'pom.xml'
        goals: 'clean verify package'
        options: >
          -DDB_URL="$(DB_URL)"
          -DDB_USERNAME="$(DB_USERNAME)"
          -DDB_PASSWORD="$(DB_PASSWORD)"
          -DDRIVER_CLASS="$(DRIVER_CLASS)"
          -DSECRET_KEY="$(SECRET_KEY)"
          -X -B
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'Build com Maven'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.21'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'Testes Maven'
      condition: succeededOrFailed()
      displayName: 'Publicar resultados dos testes'

- stage: Docker_Build_and_Push
  displayName: 'Docker Build and Push'
  dependsOn: Build_and_Test
  jobs:
  - job: Docker
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'portplacebackend-cr'
        repository: ${{ variables.IMAGE_NAME }}
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    # - task: Docker@2
    #   inputs:
    #     command: 'buildAndPush'
    #     repository: '$(IMAGE_NAME)'
    #     dockerfile: '**/Dockerfile'
    #     containerRegistry: 'portplacebackend-cr'
    #     tags: |
    #       latest
    #       $(Build.BuildId)
      env:
        IMAGE_NAME: $(imageName)
