trigger:
- feature-ahp-pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'portplacebackend'

stages:
- stage: Build_and_Test
  displayName: 'Build and Test'
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean verify package'
        options: '-B'
      displayName: 'Build com Maven'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'Testes Maven'
      condition: succeededOrFailed()
      displayName: 'Publicar resultados dos testes'

- stage: Docker_Build_and_Push
  displayName: 'Docker Build and Push'
  dependsOn: Build_and_Test
  jobs:
  - job: Docker
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(CONTAINER_REGISTRY)/$(IMAGE_NAME)'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'portplacebackend-connection'
        tags: |
          latest
          $(Build.BuildId)
      env:
        CONTAINER_REGISTRY: $(containerRegistry)
        IMAGE_NAME: $(imageName)
