@host = http://localhost:8080/api/v1

### GET EVENTO DE UM PORTFÓLIO
GET {{host}}/portfolios/1/events/1
Accept: application/json

### GET PARTICIPANTES DE UM PORTFÓLIO
GET {{host}}/portfolios/1/events/1/participants
Accept: application/json

### GET PARTICIPANTE DE UM PORTFÓLIO
GET {{host}}/portfolios/1/events/1/participants/5
Accept: application/json

### GET STAKEHOLDERS DE UM PORTFÓLIO
GET {{host}}/portfolios/1/stakeholders
Accept: application/json

### ADICIONAR PARTICIPANTE A UM EVENTO DE UM PORTFÓLIO
POST {{host}}/portfolios/1/events/1/participants
Accept: application/json
Content-Type: application/json

{
  "stakeholderId": 1,
  "responsible": true
}

### EDITAR PARTICIPANTE DE UM EVENTO
PUT {{host}}/portfolios/1/events/1/participants/1
Accept: application/json
Content-Type: application/json

{
  "stakeholderId": 1,
  "responsible": false
}

### DESABILITAR STAKEHOLDER
DELETE {{host}}/portfolios/1/events/1/participants/1
Accept: application/json

### DELETAR STAKEHOLDER
DELETE {{host}}/portfolios/1/events/1/participants/4/hard-delete
Accept: application/json
