@host = http://localhost:8080/api/v1

### GET TODOS OS PORTFÓLIOS
GET {{host}}/portfolios
Accept: application/json

### GET TODOS OS USUARIOS
GET {{host}}/users
Accept: application/json

### GET TODOS OS USUARIOS DISPONIVEIS PARA SEREM DONOS DE PORTFÓLIO
GET {{host}}/users/available-to-own-portfolio/2
Accept: application/json

### NOVOS DONOS DE PORTFÓLIO
POST {{host}}/portfolios/1/owners
Accept: application/json
Content-Type: application/json

{
    "ownersIds": [1,2,3,4]
}

### GET TODOS OS DONOS DE PORTFÓLIO
GET {{host}}/portfolios/1/owners
Accept: application/json