@host = http://localhost:8080/api/v1

### GET RISCOS DE UM PORTFÓLIO
GET {{host}}/portfolios/1/risks
Accept: application/json

### GET OCORRENCIAS DE UM RISCO
GET {{host}}/portfolios/1/risks/1/occurrences
Accept: application/json

### NOVA OCORRENCIA DE UM RISCO
POST {{host}}/portfolios/1/risks/1/occurrences
Accept: application/json
Content-Type: application/json

{
    "description": "Ocorrência de risco 1",
    "dateOfOccurrence": "2025-09-22T14:30:00Z",
    "solvedAt": "2025-09-22T14:30:00Z",
    "followedPreventionPlan": true,
    "preventionActions": "Ações de prevenção tomadas",
    "followedContingencyPlan": true,
    "contingencyActions": "Ações de contingência tomadas"
}

### ATUALIZAR OCORRENCIA DE UM RISCO
PUT {{host}}/portfolios/1/risks/1/occurrences/1
Accept: application/json
Content-Type: application/json

{
    "description": "Ocorrência de risco 1 - Atualizada",
    "dateOfOccurrence": "2025-09-21T14:30:00Z",
    "solvedAt": null,
    "followedPreventionPlan": false,
    "preventionActions": "Nenhuma ação de prevenção tomada",
    "followedContingencyPlan": false,
    "contingencyActions": "Nenhuma ação de contingência tomada"
}

### DESABILITAR OCORRENCIA DE UM RISCO
DELETE {{host}}/portfolios/1/risks/1/occurrences/1
Accept: application/json

### DELETAR OCORRENCIA DE UM RISCO
DELETE {{host}}/portfolios/1/risks/1/occurrences/1/hard-delete
Accept: application/json