@host = http://localhost:8080/api/v1

### GET TODOS OS PORTFÓLIOS
GET {{host}}/portfolios
Accept: application/json

### GET RISCOS DE UM PORTFÓLIO
GET {{host}}/portfolios/1/risks
Accept: application/json

### NOVO RISCO DE UM PORTFÓLIO
POST {{host}}/portfolios/1/risks
Accept: application/json
Content-Type: application/json

{
  "name": "Risco 2",
  "description": "Descrição do risco"
}

### ATUALIZAR RISCO DE UM PORTFÓLIO
PUT {{host}}/portfolios/1/risks/2
Accept: application/json
Content-Type: application/json

{
  "name": "Risco 2",
  "description": "Descrição do risco",
  "probability": "HIGH",
  "probabilityDescription": "é HIGH",
  "impact": "HIGH",
  "impactDescription": "é HIGH",
  "preventionPlan": "Plano de prevenção",
  "contingencyPlan": "Plano de contingência"
}


### DISABLE RISCO DE UM PORTFÓLIO
DELETE {{host}}/portfolios/1/risks/2
Accept: application/json

### DELETE RISCO DE UM PORTFÓLIO
DELETE {{host}}/portfolios/1/risks/2/hard-delete
Accept: application/json