@host = http://localhost:8080/api/v1

### GET TODOS OS PORTFÓLIOS
GET {{host}}/portfolios
Accept: application/json

### GET PORTFÓLIO
GET {{host}}/portfolios/1
Accept: application/json

### GET TODOS OS STAKEHOLDERS DE UM PORTFÓLIO
GET {{host}}/portfolios/1/stakeholders?includeDisabled=true
Accept: application/json

### GET TODOS OS STAKEHOLDERS DISPONÍVEIS PARA EVENTO
GET {{host}}/portfolios/1/stakeholders/available-for-event/2
Accept: application/json

### GET STAKEHOLDER DE UM PORTFÓLIO
GET {{host}}/portfolios/1/stakeholders/1
Accept: application/json

### GET EVENTOS DE UM STAKEHOLDER DE UM PORTFÓLIO
GET {{host}}/portfolios/1/stakeholders/1/events
Accept: application/json

### GET EVENTOS DE UM STAKEHOLDER
GET {{host}}/portfolios/1/stakeholders/2/events
Accept: application/json

### CADASTRAR STAKEHOLDER EM UM PORTFÓLIO
POST {{host}}/portfolios/1/stakeholders
Accept: application/json
Content-Type: application/json

{
  "name": "Stakeholder 4"
}

### EDITAR STAKEHOLDER DE UM PORTFÓLIO
PUT {{host}}/portfolios/1/stakeholders/1
Accept: application/json
Content-Type: application/json

{
    "name": "Stakeholder 1 Editado",
    "powerLevel": "LOW",
    "powerLevelJustification": "Justificativa do nível de poder",
    "interestLevel": "MEDIUM",
    "interestLevelJustification": "Justificativa do nível de interesse",
    "expectations": "Expectativas do portfólio",
    "obligationsWithStakeholder": "Obrigações com o stakeholder",
    "positivePoints": "Pontos positivos do portfólio",
    "negativePoints": "Pontos negativos do portfólio"
}

### DESABILITAR STAKEHOLDER
DELETE {{host}}/portfolios/1/stakeholders/2
Accept: application/json

### DELETAR STAKEHOLDER
DELETE {{host}}/portfolios/1/stakeholders/2/hard-delete
Accept: application/json
