@host = http://localhost:8080/api/v1

// COMPARAÇÃO DE CRITÉRIOS

### BUSCA DE TODAS AS AHPs
GET {{host}}/strategies/1/ahps?includeDisabled=true

### BUSCA POR ID DE UMA AHP
GET {{host}}/strategies/1/ahps/1

### CADASTRAR DE AHP
POST {{host}}/strategies/1/ahps
Content-Type: application/json

{
  "name": "AHP TESTE2605",
  "description": "Descrição TESTE2605",
  "criteriaGroupId": 3,
  "strategyId": 1
  //"projectIds": [1, 3]
}

### EDIÇÃO DE AHP
PUT {{host}}/strategies/1/ahps/2
Content-Type: application/json

{
  "name": "AHP 2 Editado",
  "description": "Descrição da AHP 2 Editada"
  //"projectIds": [1, 2]
}

### DESABILITAR AHP
DELETE  {{host}}/strategies/1/ahps/2

### DELETAR AHP
DELETE  {{host}}/strategies/1/ahps/2/hard-delete