@host = http://localhost:8080/api/v1

// COMPARAÇÃO DE CRITÉRIOS

### BUSCA DE TODAS AS AHPs
GET {{host}}/strategies/1/ahps

### BUSCA POR ID DE UMA AHP
GET {{host}}/strategies/1/ahps/1

### CADASTRAR DE AHP
POST {{host}}/strategies/1/ahps
Content-Type: application/json

{
  "name": "AHP 2",
  "description": "Descrição 2",
  "criteriaGroupId": 2,
  "strategyId": 1
  //"projectIds": [1, 3]
}

### EDIÇÃO DE AHP
PUT {{host}}/strategies/1/ahps/1
Content-Type: application/json

{
  "name": "AHP 1 Alterada",
  "description": "Descrição da AHP 1 Alterada"
  //"projectIds": [1, 2]
}

### DESABILITAR AHP
DELETE  {{host}}/strategies/1/ahps/2

### DELETAR AHP
DELETE  {{host}}/strategies/1/ahps/2/hard-delete