@host = http://localhost:8080/api/v1

// GRUPO DE CRITÉRIOS

### BUSCA DE TODOS OS CRITÉRIOS
GET {{host}}/strategies/1/criteria-groups/1/criteria

### BUSCA POR ID DE UM CRITÉRIO
GET {{host}}/strategies/1/criteria-groups/1/criteria

### CADASTRAR DE CRITÉRIO
POST {{host}}/strategies/1/criteria-groups/3/criteria/2
Content-Type: application/json

{
  "name": "CRITERIO 4",
  "description": "CRITERIO 4"
}

### EDIÇÃO DE GRUPO DE CRITÉRIOS
PUT {{host}}/strategies/1/criteria-groups/3/criteria/1
Content-Type: application/json

{
  "name": "ROI EDITADO",
  "description": "ROI EDITADO"
}

### DESABILITAR GRUPO DE CRITÉRIOS
DELETE  {{host}}/strategies/1/criteria-groups/2/criteria/3

### DELETAR GRUPO DE CRITÉRIOS
DELETE  {{host}}/strategies/1/criteria-groups/2/criteria/3/hard-delete