@host = http://localhost:8080/api/v1

### GET TODOS OS CENÁRIOS
GET {{host}}/strategies/1/scenarios
Accept: application/json

### GET CENÁRIO
GET {{host}}/strategies/1/scenarios/2
Accept: application/json

### CADASTRAR CENÁRIO
POST {{host}}/strategies/1/scenarios
Accept: application/json
Content-Type: application/json

{
  "name": "Cenário 2",
  "description": "Descrição do Cenário 2",
  "budget": 150000.00,
  "evaluationGroupId": 1,
  "portfolioId": 1
}

### EDITAR CENÁRIO
PUT {{host}}/strategies/1/scenarios/1
Accept: application/json
Content-Type: application/json

{
  "name": "Cenário 1 Editado",
  "status": "WAITING_AUTHORIZATION",
  "budget": 150000.00
}

### DESABILITAR CENÁRIO
DELETE {{host}}/strategies/1/scenarios/1
Accept: application/json

### DELETAR CENÁRIO
DELETE {{host}}/strategies/1/scenarios/1/hard-delete
Accept: application/json
