@host = http://localhost:8080/api/v1

### GET TODOS OS OBJETIVOS
GET {{host}}/strategies/2/strategic-objectives
Accept: application/json

### GET OBJETIVO ESTRATÉGICO
GET {{host}}/strategies/1/strategic-objectives/1
Accept: application/json

### CADASTRAR OBJETIVO ESTRATÉGICO
POST {{host}}/strategies/2/strategic-objectives
Accept: application/json
Content-Type: application/json

{
  "name": "Objetivo Estratégico 2",
  "description": "Descrição do Objetivo Estratégico 2"
}

### EDITAR OBJETIVO ESTRATÉGICO
PUT {{host}}/strategies/2/strategic-objectives/4
Accept: application/json
Content-Type: application/json

{
  "name": "Objetivo Estratégico 4 Editado",
  "description": "Descrição do Objetivo Estratégico 4 Editado",
  "status": "ACTIVE"
}

### DESABILITAR OBJETIVO ESTRATÉGICO
DELETE {{host}}/strategies/2/strategic-objectives/2
Accept: application/json

### DELETAR OBJETIVO ESTRATÉGICO
DELETE {{host}}/strategies/1/hard-delete/strategic-objectives/1
Accept: application/json
