@host = http://localhost:8080/api/v1

### GET TODAS AS ESTRATÉGIAS
GET {{host}}/strategies?status=ACTIVE&includeDisabled=true&searchQuery=estratégia 4
Accept: application/json

### GET ESTRATÉGIA
GET {{host}}/strategies/1
Accept: application/json

### CADASTRAR ESTRATÉGIA
POST {{host}}/strategies
Accept: application/json
Content-Type: application/json

{
  "name": "Estratégia 4",
  "description": "Descrição do Estratégia 4"
}

### EDITAR ESTRATÉGIA
PUT {{host}}/strategies/3
Accept: application/json
Content-Type: application/json

{
  "name": "Estratégia 3 EDITADA",
  "description": "Descrição do Estratégia 3 EDITADA",
  "status": "INACTIVE"
}

### DESABILITAR ESTRATÉGIA
DELETE {{host}}/strategies/4
Accept: application/json

### DELETAR ESTRATÉGIA
DELETE {{host}}/strategies/1/hard-delete
Accept: application/json
