@host = http://localhost:8080/api/v1

### GET TODOS OS OBJETIVOS
GET {{host}}/strategies/1/strategic-objectives

### GET OBJETIVO ESTRATÉGICO
GET {{host}}/strategies/1/strategic-objectives/3
Accept: application/json

### GET CRITERIOS RELACIONADOS AO OBJETIVO ESTRATÉGICO
GET {{host}}/strategies/1/strategic-objectives/3/criteria
Accept: application/json

### GET PORTFOLIOS RELACIONADOS AO OBJETIVO ESTRATÉGICO
GET {{host}}/strategies/1/strategic-objectives/1/portfolios
Accept: application/json

### GET PROJETOS RELACIONADOS AO OBJETIVO ESTRATÉGICO
GET {{host}}/strategies/1/strategic-objectives/1/projects
Accept: application/json

### CADASTRAR OBJETIVO ESTRATÉGICO
POST {{host}}/strategies/1/strategic-objectives
Accept: application/json
Content-Type: application/json

{
  "name": "Objetivo Estratégico 3",
  "description": "Descrição do Objetivo Estratégico 3"
}

### EDITAR OBJETIVO ESTRATÉGICO
PUT {{host}}/strategies/2/strategic-objectives/4
Accept: application/json
Content-Type: application/json

{
  "name": "Objetivo Estratégico 4 Editado",
  "description": "Descrição do Objetivo Estratégico 4 Editado",
  "status": "ACTIVE"
}

### DESABILITAR OBJETIVO ESTRATÉGICO
DELETE {{host}}/strategies/2/strategic-objectives/2
Accept: application/json

### DELETAR OBJETIVO ESTRATÉGICO
DELETE {{host}}/strategies/1/hard-delete/strategic-objectives/1
Accept: application/json
