@host = http://localhost:8080/api/v1
# @host = https://portplace-backend.greenstone-ec062121.brazilsouth.azurecontainerapps.io/api/v1

// GRUPO DE CRITÉRIOS

### BUSCA DE TODOS OS GRUPOS DE CRITÉRIOS
GET {{host}}/strategies/1/criteria-groups

### BUSCA POR ID DE UM GRUPO DE CRITÉRIOS
GET {{host}}/strategies/1/criteria-groups/2

### VERIFICA SE O GRUPO DE CRITÉRIOS ESTÁ PRONTO PARA SER USADO
GET {{host}}/strategies/1/criteria-groups/2/ready

### CADASTRAR GRUPO DE CRITÉRIOS
POST {{host}}/strategies/1/criteria-groups
Content-Type: application/json

{
  "name": "Grupo de critérios 2",
  "description": "Grupo de critérios 2"
}

### EDIÇÃO DE GRUPO DE CRITÉRIOS
PUT {{host}}/strategies/2/criteria-groups/4
Content-Type: application/json

{
  "name": "Grupo de critérios 4 atualizado",
  "description": "Grupo de critérios 4",
  "status": "ACTIVE"
}

### DESABILITAR GRUPO DE CRITÉRIOS
DELETE {{host}}/strategies/1/criteria-groups/3

### DELETAR GRUPO DE CRITÉRIOS
DELETE {{host}}/strategies/1/criteria-groups/1/hard-delete