@host = http://localhost:8080/api/v1

### LOGIN
POST {{host}}/users/authenticate
Content-Type: application/json

{
  "email": "gabrielgmns071204@gmail.com",
  "password": "12345"
}

### GET TODAS SOLICITAÇÕES DE RECURSOS
GET {{host}}/allocation-requests?resourceId=1
Accept: application/json

### GET SOLICITAÇÃO DE RECURSO ESPECÍFICO
GET {{host}}/allocation-requests/5
Accept: application/json

### GET TODOS AS POSIÇÕES
GET {{host}}/positions
Accept: application/json

### NOVA SOLICITAÇÃO DE RECURSO
POST {{host}}/allocation-requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUE1PX0FETSIsIm5hbWUiOiJHYWJyaWVsIE1hcnRpbnMgTnVuZXMgZGEgU2lsdmEiLCJlbWFpbCI6ImdhYnJpZWxnbW5zMDcxMjA0QGdtYWlsLmNvbSIsInN1YiI6ImdhYnJpZWxnbW5zMDcxMjA0QGdtYWlsLmNvbSIsImlhdCI6MTc2MDUzMjM5MywiZXhwIjoxNzYwNTM1OTkzfQ.Dd6BPqIMKKO8Opd-Nuy0P7WhBkjQ0-sJp3XycnBMr-Q

{
    "startDate": "2025-01-01",
    "endDate": "2025-01-01",
    "dailyHours": 8,
    "priority": "HIGH",
    "positionId": 2,
    "projectId": 2
}

### EDITAR SOLICITAÇÃO DE RECURSO
PUT {{host}}/allocation-requests/4
Content-Type: application/json

{
    "startDate": "2024-12-31",
    "endDate": "2027-04-04",
    "dailyHours": 2,
    "priority": "MEDIUM",
    "positionId": 1
}

### DESABILITAR RECURSO
DELETE {{host}}/allocation-requests/2
Content-Type: application/json

### DELETAR RECURSO
DELETE {{host}}/allocation-requests/1/hard-delete
Content-Type: application/json