@host = http://localhost:8080/api/v1

### GET TODAS ALOCAÇÕES DE RECURSOS
GET {{host}}/allocations?startDate=2025-01-01&endDate=2029-01-01
Accept: application/json

### GET TODAS ALOCAÇÕES DE RECURSOS
GET {{host}}/allocations/analytics?startDate=2028-01-01&endDate=2028-01-07&projectId=2&resourceId=1
Accept: application/json

### GET TODAS ALOCAÇÕES DE RECURSOS
GET {{host}}/allocations/analytics?startDate=2026-01-01&endDate=2026-01-02&resourceId=1
Accept: application/json

### GET ALOCAÇÃO DE RECURSO
GET {{host}}/allocations/1
Accept: application/json

### GET TODOS AS SOLICITAÇÕES DE RECURSOS
GET {{host}}/allocation-requests
Accept: application/json

### NOVA ALOCAÇÃO DE RECURSO
POST {{host}}/allocations
Content-Type: application/json

{
    "startDate": "2025-01-01",
    "endDate": "2025-01-01",
    "dailyHours": 12,
    "resourceId": 2,
    "allocationRequestId": 2
}

### EDITAR ALOCAÇÃO DE RECURSO
PUT {{host}}/allocations/4
Content-Type: application/json

{
    "startDate": "2028-01-01",
    "endDate": "2028-01-07",
    "dailyHours": 12,
    "resourceId": 1,
    "cancelled": true
}

### EDITAR ALOCAÇÃO DE RECURSO
PATCH {{host}}/allocations/2/cancel
Content-Type: application/json

### DELETAR ALOCAÇÃO DE RECURSO
DELETE {{host}}/allocations/1
Content-Type: application/json
