@host = http://localhost:8080/api/v1

### GET TODAS ALOCAÇÕES DE RECURSOS
GET {{host}}/allocations
Accept: application/json

### GET TODAS ALOCAÇÕES DE RECURSOS
GET {{host}}/allocations/analytics?startDate=2026-01-01&endDate=2028-01-07
Accept: application/json

### GET ALOCAÇÃO DE RECURSO
GET {{host}}/allocations/2
Accept: application/json

### GET TODOS AS SOLICITAÇÕES DE RECURSOS
GET {{host}}/allocation-requests
Accept: application/json

### NOVA ALOCAÇÃO DE RECURSO
POST {{host}}/allocations
Content-Type: application/json

{
    "startDate": "01/01/2026",
    "endDate": "01/01/2026",
    "dailyHours": 2,
    "resourceId": 2,
    "allocationRequestId": 4
}

### EDITAR ALOCAÇÃO DE RECURSO
PUT {{host}}/allocations/3
Content-Type: application/json

{
    "startDate": "01/01/2026",
    "endDate": "07/01/2026",
    "dailyHours": 7,
    "resourceId": 1
}

### DELETAR ALOCAÇÃO DE RECURSO
DELETE {{host}}/allocations/1
Content-Type: application/json
