@host = http://localhost:8080/api/v1

### REGISTER
POST {{host}}/users/register
Content-Type: application/json

{
  "name": "Gabriel Martins",
  "email": "gabrielgmns071204@gmail.com",
  "password": "12345",
  "role": "PMO_ADM"
}

### LOGIN
POST {{host}}/users/authenticate
Content-Type: application/json

{
  "email": "gabrielgmns071204@gmail.com",
  "password": "123s45"
}


### BUSCA DE USUÁRIOS
GET  {{host}}/users?page=0&size=1
Host: localhost:8080

### BUSCA DE USUÁRIO POR ID
GET  {{host}}/users/1
Host: localhost:8080


### Alterar dados do usuário
PUT {{host}}/users/1
Content-Type: application/json

{
  "name": "Gabriel Martins Nunes da Silva",
  "password": "12345",
  "status": "INACTIVE"
}

### DELETAR USUÁRIO
DELETE {{host}}/users/510