@host = http://localhost:8080/api/v1

### REGISTER
POST {{host}}/users/register
Content-Type: application/json

{
  "name": "Joao Silva",
  "email": "joao@example.com",
  "password": "12345",
  "role": "PROJECT_MANAGER"
}

### LOGIN
POST {{host}}/users/authenticate
Content-Type: application/json

{
  "email": "joao@example.com",
  "password": "12345"
}


### BUSCA DE USUÁRIOS
GET  {{host}}/users?includeDisabled=true
Host: localhost:8080

### BUSCA DE USUÁRIO POR ID
GET  {{host}}/users/1
Host: localhost:8080


### Alterar dados do usuário
PUT {{host}}/users/2
Content-Type: application/json

{
  "name": "Joao Silva",
  "password": "12345",
  "status": "ACTIVE"
}

### DELETAR USUÁRIO
DELETE {{host}}/users/2

### DELETAR USUÁRIO
DELETE {{host}}/users/2/hard-delete