@host = http://localhost:8080/api/v1

### CADASTRAR AHP
POST {{host}}/ahp
Content-Type: application/json

### BUSCA DE AHPS
GET  {{host}}/ahp?
Accept: application/json
Host: localhost:8080

### BUSCA DE AHP POR ID
GET  {{host}}/ahp/1
Accept: application/json
Host: localhost:8080

### DESABILITAR AHP
DELETE {{host}}/ahp/2

### DELETAR AHP
DELETE {{host}}/ahp/2/hard-delete



//------------------------------------
// CRITERIOS
//------------------------------------
### CADASTRAR CRITERIO
POST {{host}}/ahp/4/criteria
Content-Type: application/json

{
    "name": "Criterio 4.1",
    "description": "Descricao do criterio 4.1"
}

### BUSCA DE CRITERIOS
GET  {{host}}/ahp/4/criteria?includeDisabled=false

### BUSCA DE CRITERIO POR ID
GET  {{host}}/ahp/4/criteria/5

### ATUALIZAR CRITERIO
PUT {{host}}/ahp/4/criteria/5
Content-Type: application/json

{
    "name": "Criterio 4.2",
    "description": "Descricao do criterio 4.2"
}


### DESABILITAR CRITERIO
DELETE {{host}}/ahp/3/criteria/3

### DELETAR CRITERIO
DELETE {{host}}/ahp/3/criteria/2/hard-delete


//------------------------------------
// COMPARAÇÃO DE CRITÉRIOS
//------------------------------------
### CADASTRAR COMPARAÇÃO DE CRITÉRIOS
POST {{host}}/ahp/4/criteriaComparisons
Content-Type: application/json

{
    "comparedCriterionId": 4,
    "referenceCriterionId": 5,
    "importanceScale": "EXTREMELY_MORE_IMPORTANT",
    "ahpId": 4
}

### BUSCA DE COMPARAÇÃO DE CRITÉRIOS
GET  {{host}}/ahp/4/criteriaComparisons?includeDisabled=true

### BUSCA DE COMPARAÇÃO DE CRITÉRIOS POR ID
GET  {{host}}/ahp/4/criteriaComparisons/1

### ATUALIZAR COMPARAÇÃO DE CRITÉRIOS
PUT {{host}}/ahp/4/criteriaComparisons/1
Content-Type: application/json

{
    "importanceScale": "MUCH_LESS_IMPORTANT"
}

### DESABILITAR COMPARAÇÃO DE CRITÉRIOS
DELETE {{host}}/ahp/4/criteriaComparisons/1

### DELETAR COMPARAÇÃO DE CRITÉRIOS
DELETE {{host}}/ahp/4/criteriaComparisons/2/hard-delete