@host = http://localhost:8080/api/v1

### CADASTRAR PROJETO
POST {{host}}/projects
Content-Type: application/json

{
  "name": "Projeto 2 TESTE2605",
  "description": "Projeto  2 TESTE2605TESTE2605TESTE2605TESTE2605",
  "startDate": "2023-10-01",
  "endDate": "2023-12-31",
  "status": "IN_PROGRESS",
  "projectManager": 1,
  "earnedValue": 152752.87,
  "plannedValue": 25781.90,
  "actualCost": 25440.00,
  "budget": 150000.00,
  "payback": 124521.13
}

### BUSCA DE PROJETOS
GET  {{host}}/projects
Accept: application/json
Host: localhost:8080

### BUSCA DE PROJETO POR ID
GET  {{host}}/projects/1
Accept: application/json
Host: localhost:8080


### ALTERAR PROJETO
PUT {{host}}/projects/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "Projeto Portplace",
  "description": "Projeto de gerenciaasdasdmento de portfólio",
  "status": "IN_PROGRESS",
  "earnedValue": 152752.87,
  "plannedValue": 25781.90,
  "actualCost": 25440.00,
  "budget": 150000.00,
  "payback": 124521.13,
  "startDate": "2023-10-01",
  "endDate": "2023-12-31",
  "projectManager": 1
}

### DELETAR PROJETO
DELETE {{host}}/projects/5