@host = http://localhost:8080/api/v1

### CADASTRAR PROJETO
POST {{host}}/projects
Content-Type: application/json

{
  "name": "Projeto 1",
  "description": "Projeto 1",
  "payback": 124521.13,
  "roi": {{$randomInt 0 12}},

  "earnedValue": 500000.0,
  "plannedValue": 100.0,
  "actualCost": 0.00,
  "budgetAtCompletion": 1000000.00,  

  "startDate": "01/01/2023",
  "endDate": "31/12/2023"
}


### BUSCA DE PROJETOS
GET  {{host}}/projects
Accept: application/json
Host: localhost:8080

### BUSCA DE PROJETO POR ID
GET  {{host}}/projects/4
Accept: application/json
Host: localhost:8080


### CANCELAR PROJETO
PATCH {{host}}/projects/5/cancel
Accept: application/json
Content-Type: application/json

{
  "cancellationReason": "Mudança de escopo"
}

### ALTERAR PROJETO
PUT {{host}}/projects/1
Accept: application/json
Content-Type: application/json

{
  "name": "Projeto 1 Alterado",
  "description": "Projeto 1 descrição alterada",
  "payback": "150000.0",
  "roi": "10.5",
  
  "budgetAtCompletion": "150000.0",
  "earnedValue": "75.0",
  "plannedValue": "75000.0",
  "actualCost": "70000.0",

  "startDate": "01/01/2024",
  "endDate": "31/12/2025"
}

### DELETAR PROJETO
DELETE {{host}}/projects/11