@host = http://localhost:8080/api/v1

### CADASTRAR PROJETO
POST {{host}}/projects
Content-Type: application/json

{
  "name": "Projeto 3",
  "description": "Projeto 3",
  "status": "IN_ANALYSIS",

  "earnedValue": 10.0,
  "plannedValue": 123456.78,
  "currentPlannedValue": 10.0,
  "actualCost": 10.00,
  "budget": 150000.00,  

  "startDate": "2023-10-01",
  "endDate": "2023-12-31",
  "projectManager": 1,
  "payback": 124521.13
}


### BUSCA DE PROJETOS
GET  {{host}}/projects
Accept: application/json
Host: localhost:8080

### BUSCA DE PROJETOS POR GERENTE DE PROJETO
GET  {{host}}/projects/manager/1?includeDisabled=true
Accept: application/json
Host: localhost:8080


### BUSCA DE PROJETO POR ID
GET  {{host}}/projects/1
Accept: application/json
Host: localhost:8080


### ALTERAR PROJETO
PUT {{host}}/projects/1
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "name": "Projeto 1 Alterado",
  "description": "Projeto 1 descrição alterada",
  "status": "COMPLETED",
  "payback": "150000.0",
  "budget": "150000.0",
  "startDate": "2020-10-01",
  "endDate": "2025-12-31",
  "projectManager": 1
}

### DELETAR PROJETO
DELETE {{host}}/projects/11