@host = http://localhost:8080/api/v1

### CADASTRAR PROJETO
POST {{host}}/projects
Content-Type: application/json

{
  "name": "Projeto 3",
  "description": "Projeto 3",
  "status": "IN_ANALYSIS",

  "earnedValue": 10.0,
  "plannedValue": 123456.78,
  "currentPlannedValue": 10.0,
  "actualCost": 10.00,
  "budget": 150000.00,  

  "startDate": "2023-10-01",
  "endDate": "2023-12-31",
  "payback": 124521.13
}


### BUSCA DE PROJETOS
GET  {{host}}/projects
Accept: application/json
Host: localhost:8080

### BUSCA DE PROJETO POR ID
GET  {{host}}/projects/2
Accept: application/json
Host: localhost:8080


### ALTERAR PROJETO
PUT {{host}}/projects/3
Accept: application/json
Content-Type: application/json

{
  "name": "Projeto 3 Alterado",
  "description": "Projeto 3 descrição alterada",
  "status": "IN_PROGRESS",
  "payback": "150000.0",
  
  "budgetAtCompletion": "150000.0",
  "earnedValue": "75000.0",
  "plannedValue": "75000.0",
  "actualCost": "70000.0",

  "startDate": "01/01/2024",
  "endDate": "31/12/2025"
}

### DELETAR PROJETO
DELETE {{host}}/projects/11